/* Schema 4 Lite workflow, UI, persistence, and regression hooks. */
(function installSchema4UI(){
  "use strict";
  const S=window.Schema4Lite,L=S.legacy;
  function invalidateBlue(reason){if(state.results.blue_closing){if(!state.meta.stale.includes("blue_closing"))state.meta.stale.push("blue_closing");state.resultMeta.blue_closing.status="stale";}debugLog("final-blue-invalidated",{reason});}

  markDependentsStale=function(id,onlyExisting=true){L.markDependentsStale(id,onlyExisting);if(id==="green"){S.initializeCandidateSelection(true);state.candidateSelection.state="pending";invalidateBlue("green-changed");}};
  runHat=async function(id,opt={}){
    if(id==="blue_closing"){const v=S.validateCandidateSelection();if(state.candidateSelection?.state!=="confirmed"||!v.valid){showGlobalNotice(v.errors[0]||"緑の結論候補を確定してください。","error");renderAll();return {ok:false,continue:false};}}
    const result=await L.runHat(id,opt);
    if(id==="green"&&result.ok){S.initializeCandidateSelection(true);const auto=state.candidateSelection.items.length<=3&&state.candidateSelection.items.every(x=>x.disposition==="include");if(state.input.mode==="quick"&&auto){state.candidateSelection.state="confirmed";state.candidateSelection.confirmedAt=now();}else{state.candidateSelection.state="pending";result.continue=false;}await queueAutosave("candidate-selection-initialized");renderAll();}
    return result;
  };
  startFreshWorkflow=async function(){state.candidateSelection=S.freshSelection();return L.startFreshWorkflow();};

  function setDisposition(ideaId,disposition){
    const item=arr(state.candidateSelection?.items).find(x=>x.ideaId===ideaId);if(!item)return;const chosen=state.candidateSelection.items.filter(x=>["include","conditional"].includes(x.disposition)&&x.ideaId!==ideaId).length;
    if(["include","conditional"].includes(disposition)&&chosen>=3){showGlobalNotice("最終比較候補は最大3件です。別の案を除外してください。","error");return;}
    if(item.autoDisposition==="exclude"&&disposition!=="exclude"&&!window.confirm("この案はAIにより制約違反または対象外抵触と評価されています。結論候補へ戻しますか？"))return;
    item.disposition=disposition;item.changedBy="user";item.updatedAt=now();if(!item.reasons.some(x=>x.code==="user_override"))item.reasons.push({code:"user_override",relatedIds:[]});state.candidateSelection.state="pending";state.candidateSelection.confirmedAt=null;invalidateBlue("candidate-selection-changed");renderAll();queueAutosave("candidate-selection-changed");
  }
  async function confirmSelection(){const v=S.validateCandidateSelection();if(!v.valid){showGlobalNotice(v.errors[0],"error");return;}state.candidateSelection.state="confirmed";state.candidateSelection.confirmedAt=now();debugLog("candidate-selection-confirmed",{candidateIds:v.candidateIds});await queueAutosave("candidate-selection-confirmed");renderAll();if(state.runSummary)state.runSummary.status="running";await runHat("blue_closing",{workflow:true});}
  function candidateHtml(){
    if(!state.results.green)return "";S.initializeCandidateSelection(false);const byId=new Map(arr(state.results.green.ideas).map(x=>[x.ideaId,x])),items=state.candidateSelection.items,chosen=items.filter(x=>["include","conditional"].includes(x.disposition)).length;
    const cards=items.map(item=>{const idea=byId.get(item.ideaId),reasons=arr(item.reasons).filter(x=>x.code!=="user_override").map(S.reasonLabel);return `<div class="subcard"><h4>${esc(idea?.name||item.ideaId)} <span class="metaBadge">${esc(item.ideaId)}</span> <span class="score">AI初期値：${esc(label(item.autoDisposition))}</span></h4>${reasons.length?`<small>${reasons.map(esc).join(" / ")}</small>`:""}<div class="actions"><button class="btn small ${item.disposition==="include"?"primary":""}" data-candidate="include" data-idea="${esc(item.ideaId)}">含める</button><button class="btn small ${item.disposition==="conditional"?"primary":""}" data-candidate="conditional" data-idea="${esc(item.ideaId)}">条件付き</button><button class="btn small ${item.disposition==="exclude"?"danger":""}" data-candidate="exclude" data-idea="${esc(item.ideaId)}">除外</button></div></div>`;}).join("");
    return `<div class="section candidateSelection"><h3>最終青の比較候補</h3><p>候補を1～3件に絞ってください。除外案は最終青へ送信されません。</p><p><strong>選択中：${chosen} / 3</strong></p>${cards}<div class="actions"><button class="btn" data-act="reset-candidates">初期値に戻す</button><button class="btn primary" data-act="confirm-candidates" ${chosen<1||chosen>3?"disabled":""}>候補を確定して最終青へ</button></div></div>`;
  }

  renderResult=function(id,r){
    if(id==="green")return L.renderResult(id,r)+(r.combinationSuggestion?textBlock("組合せの発想メモ",r.combinationSuggestion)+`<p class="notice">この組合せは結論候補へ自動追加されません。</p>`:"")+candidateHtml();
    if(id!=="blue_closing")return L.renderResult(id,r);
    const selected=r.selectedIdea||{},decision=`<div class="recommend"><strong>${esc(label(r.decisionType))}</strong><p>推奨案：${esc(selected.name||"—")}</p></div>`,overview=textBlock("案の概要",selected.description),reasons=list("主な理由",r.keyReasons),table=arr(r.evaluations).length?`<div class="section"><h3>候補比較</h3><table class="optionTable"><thead><tr><th>案</th><th>主な理由</th><th>主なリスク</th><th>実現性</th><th>推奨度</th></tr></thead><tbody>${r.evaluations.map(e=>{const idea=arr(state.results.green?.ideas).find(x=>x.ideaId===e.ideaId);return `<tr><td>${esc(idea?.name||e.ideaId)}</td><td>${esc(e.mainReason)}</td><td>${esc(e.mainRisk)}</td><td>${scoreDisplay(e.feasibility)}</td><td>${scoreDisplay(e.recommendationScore)}</td></tr>`;}).join("")}</tbody></table><p><small>評価値はGemini Nanoによる参考評価です。</small></p></div>`:"",actions=arr(r.selectedActions).length?`<div class="section"><h3>着手候補</h3><ol>${r.selectedActions.map(x=>`<li><strong>${esc(x.text)}</strong><br><span class="hatState">${esc(x.actionId)}</span></li>`).join("")}</ol></div>`:"";
    return decision+overview+reasons+table+actions+list("推奨案の必要条件",r.successConditions)+(arr(r.topRisks).length?`<div class="section"><h3>主要リスク</h3>${r.topRisks.map(x=>`<div class="subcard"><strong>${esc(x.name)}</strong><p>${esc(x.cause)}</p></div>`).join("")}</div>`:"")+list("不足情報",arr(r.missingInformation).map(x=>x.text))+`<div class="section"><h3>情報充足度（ハーネス計算）</h3><div class="meter"><span style="width:${Math.max(0,Math.min(100,Number(r.informationCompleteness)||0))}%"></span></div><p>${esc(r.informationCompleteness)} / 100</p></div>`;
  };
  renderCard=function(h){let html=L.renderCard(h);if(h.id==="green"&&state.candidateSelection?.state!=="confirmed")html=html.replace(/<button class="btn primary" data-act="next" data-hat="blue_closing">[\s\S]*?<\/button>/,"");if(h.id==="blue_closing")html=html.replace(/<button class="btn small" data-act="edit" data-hat="blue_closing">編集<\/button>/,"");return html;};
  bindCardActions=function(){L.bindCardActions();$$('[data-candidate]').forEach(b=>b.onclick=()=>setDisposition(b.dataset.idea,b.dataset.candidate));$$('[data-act="confirm-candidates"]').forEach(b=>b.onclick=confirmSelection);$$('[data-act="reset-candidates"]').forEach(b=>b.onclick=()=>{S.initializeCandidateSelection(true);invalidateBlue("candidate-reset");renderAll();queueAutosave("candidate-reset");});};
  continueAfterWarning=async function(){const id=$("#warningContinueBtn").dataset.hat;if(id!=="green")return L.continueAfterWarning();for(const w of arr(state.resultMeta.green?.validation?.warnings))w.acknowledged=true;state.resultMeta.green.userAcceptedWarnings=true;$("#warningDialog").close();S.initializeCandidateSelection(false);state.meta.status="awaiting_review";state.meta.pendingNextHat="blue_closing";renderAll();await queueAutosave("green-warning-reviewed");};

  migrateState=function(input,source="unknown"){const schema=Number(input?.schemaVersion||input?.build?.schemaVersion||0);if(schema!==4)throw new Error("このJSONは旧Schemaです。v1.3.0ではSchema 4の会議データだけを読み込めます。");const next=S.ensureState(clone(input));next.deterministic=next.deterministic||extractDeterministicInput(next.input);next.decisionBoundary=next.decisionBoundary||{criteria:[],outOfScope:[]};next.results=next.results||{};next.resultMeta=Object.fromEntries(HAT_IDS.map(id=>[id,{...freshResultMeta(),...(next.resultMeta?.[id]||{})}]));debugLog("schema4-load",{source,meetingId:next.id});return next;};
  migrateStoredMeetings=function(){try{const raw=storage.getItem(STORAGE_KEY);if(!raw)return;const all=JSON.parse(raw),valid={};for(const [id,x] of Object.entries(all)){try{valid[id]=migrateState(x,"storage");}catch(e){debugLog("schema4-storage-skip",{meetingId:id,error:errorData(e)});}}storage.setItem(STORAGE_KEY,JSON.stringify(valid));}catch(e){debugLog("schema4-storage-error",{error:errorData(e)});}};
  runTestAssertions=function(test=state.test){const report=L.runTestAssertions(test),add=(id,labelText,pass,actual,expected)=>report.assertions.push({id,label:labelText,status:pass?"PASS":"FAIL",actual,expected});if(state.results.green){const v=S.validateCandidateSelection();add("candidate_selection","結論候補の確定",v.valid&&state.candidateSelection.state==="confirmed",{state:state.candidateSelection.state,errors:v.errors},"confirmed");}if(state.results.blue_closing){const ids=S.selectedPairs().map(x=>x.idea.ideaId),selected=state.results.blue_closing.modelResult?.selectedIdeaId;add("selected_idea_allowed","推奨案が確定候補内",ids.includes(selected),selected,ids);}report.summary.status=report.assertions.every(x=>x.status==="PASS")?"PASS":"FAIL";return report;};
  debugLog("schema4-lite-installed",{appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION});
})();
