function addRuntimeMarkup(){
  const modeField=$("#mode")?.closest(".grid2");if(modeField&&!$("#warningPolicy")){modeField.insertAdjacentHTML("afterend",`<div class="grid2"><div class="field"><label for="warningPolicy">クイックモードの停止方針</label><select id="warningPolicy"><option value="blocking_only">エラー時のみ停止</option><option value="review_required" selected>要確認警告で一時停止</option><option value="each_hat">帽子ごとに確認</option></select></div><div class="field"><label>ビルド</label><div class="input buildInfo">v${APP_VERSION} / Schema ${SCHEMA_VERSION}</div></div></div>`);}
  const dialogs=`<dialog id="resumeDialog"><div class="dialogHead"><h2>会議を続けますか</h2><button class="btn small" data-close="resumeDialog">閉じる</button></div><div class="dialogBody"><p>保存済みの結果があります。続きから再開するか、結果を破棄して最初から実行してください。</p></div><div class="dialogFoot"><button class="btn" id="resumeCancelBtn">キャンセル</button><button class="btn" id="restartWorkflowBtn">最初から再生成</button><button class="btn primary" id="resumeWorkflowBtn">続きから再開</button></div></dialog>
  <dialog id="newMeetingDialog"><div class="dialogHead"><h2>新しい会議</h2></div><div class="dialogBody"><p>現在の会議を閉じて新規作成しますか。保存済みデータは履歴に残ります。</p></div><div class="dialogFoot"><button class="btn" data-close="newMeetingDialog">キャンセル</button><button class="btn primary" id="confirmNewMeetingBtn">新規作成</button></div></dialog>
  <dialog id="warningDialog"><div class="dialogHead"><h2 id="warningDialogTitle">確認が必要です</h2></div><div class="dialogBody" id="warningDialogBody"></div><div class="dialogFoot"><button class="btn" data-close="warningDialog">一時停止</button><button class="btn primary" id="warningContinueBtn">警告を確認して続行</button></div></dialog>
  <dialog id="importModeDialog"><div class="dialogHead"><h2>テストモード</h2><button class="btn small" data-close="importModeDialog">閉じる</button></div><div class="dialogBody"><p id="importModeMessage"></p><div class="actions"><button class="btn" data-import-mode="display">表示テスト</button><button class="btn" data-import-mode="migration">移行テスト</button><button class="btn primary" data-import-mode="generation">生成テスト</button></div></div></dialog>
  <dialog id="testReportDialog"><div class="dialogHead"><h2>テストレポート</h2><button class="btn small" data-close="testReportDialog">閉じる</button></div><div class="dialogBody" id="testReportBody"></div><div class="dialogFoot"><button class="btn" id="downloadTestReportJson">JSON保存</button><button class="btn primary" id="downloadTestReportMd">Markdown保存</button></div></dialog>`;
  document.body.insertAdjacentHTML("beforeend",dialogs);
}

window.addEventListener("error",e=>debugLog("window-error",{message:e.message,filename:e.filename,lineno:e.lineno,colno:e.colno,error:e.error?errorData(e.error):null}));
window.addEventListener("unhandledrejection",e=>debugLog("unhandled-rejection",{reason:e.reason instanceof Error?errorData(e.reason):String(e.reason)}));
document.addEventListener("visibilitychange",()=>{if(!document.hidden)updateElapsedDisplay();});

addRuntimeMarkup();
debugLog("app-start",{userAgent:navigator.userAgent,location:location.href});
migrateStoredMeetings();
hashBuildAssets().then(()=>renderSidebar());
injectDeveloperPanel();

$("#startBtn").onclick=startMeeting;$("#sampleBtn").onclick=sample;$("#clearBtn").onclick=clearInputs;$("#newBtn").onclick=newMeeting;$("#saveBtn").onclick=saveLocal;$("#historyBtn").onclick=()=>{renderHistory();$("#historyDialog").showModal();};$("#exportBtn").onclick=()=>$("#exportDialog").showModal();
$("#themeBtn").onclick=()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==="dark"?"light":"dark";storage.setItem("sixHatsTheme",d.dataset.theme);};$("#editSaveBtn").onclick=saveEdit;
$("#downloadJson").onclick=()=>download(`six-hats-meeting-v${APP_VERSION}.json`,JSON.stringify(state,null,2),"application/json");$("#downloadMd").onclick=()=>download("six-hats-meeting.md",markdown(),"text/markdown");$("#copyMd").onclick=()=>navigator.clipboard.writeText(markdown());
$("#openDebugLog").onclick=()=>{const scope=$("#debugScope")?.value||"current_run";$("#debugLogText").value=debugText(false,scope);$("#debugDialog").showModal();};$("#downloadDebugLog").onclick=()=>{const scope=$("#debugScope")?.value||"current_run";download(`six-hats-debug-${new Date().toISOString().replace(/[:.]/g,"-")}.json`,debugText(false,scope),"application/json");};$("#downloadDebugLogRedacted").onclick=()=>{const scope=$("#debugScope")?.value||"current_run";download(`six-hats-debug-redacted-${new Date().toISOString().replace(/[:.]/g,"-")}.json`,debugText(true,scope),"application/json");};$("#clearDebugLog").onclick=()=>{debugEvents.length=0;debugLog("log-cleared");};$("#copyDebugLog").onclick=()=>navigator.clipboard.writeText($("#debugLogText").value);$("#saveDebugLogFromDialog").onclick=()=>download(`six-hats-debug-${new Date().toISOString().replace(/[:.]/g,"-")}.json`,$("#debugLogText").value,"application/json");
$("#importFile").onchange=e=>e.target.files[0]&&importState(e.target.files[0]);
$("#resumeWorkflowBtn").onclick=()=>{$("#resumeDialog").close();resumeWorkflow();};$("#restartWorkflowBtn").onclick=()=>{$("#resumeDialog").close();startFreshWorkflow();};$("#resumeCancelBtn").onclick=()=>$("#resumeDialog").close();$("#confirmNewMeetingBtn").onclick=()=>{$("#newMeetingDialog").close();resetMeeting();};$("#warningContinueBtn").onclick=continueAfterWarning;
$$('[data-import-mode]').forEach(b=>b.onclick=()=>runImportMode(b.dataset.importMode));$("#downloadTestReportJson").onclick=()=>currentTestReport&&download(`six-hats-test-report-${currentTestReport.testCaseId}.json`,JSON.stringify(currentTestReport,null,2),"application/json");$("#downloadTestReportMd").onclick=()=>currentTestReport&&download(`six-hats-test-report-${currentTestReport.testCaseId}.md`,testReportMarkdown(currentTestReport),"text/markdown");
if(!$("#debugScope")){const field=$("#openDebugLog")?.closest(".field");field?.insertAdjacentHTML("afterbegin",`<div class="field"><label for="debugScope">ログ範囲</label><select id="debugScope"><option value="current_run">現在の実行</option><option value="meeting">現在の会議</option><option value="all">アプリ起動後の完全ログ</option></select></div>`);}
$$('[data-close]').forEach(b=>b.onclick=()=>$("#"+b.dataset.close)?.close());
const theme=storage.getItem("sixHatsTheme");if(theme)document.documentElement.dataset.theme=theme;
bindInput();syncInputs();renderAll();detectAI();
window.__sixHatsSelfTest=()=>{const old=clone(state);state.deterministic=extractDeterministicInput({...state.input,stakeholders:"住民、職員、議会"});state.decisionBoundary={criteria:[],outOfScope:[]};const results={};for(const id of HAT_IDS){const variant=id==="red"?selectRedSchemaVariant(state.deterministic.stakeholders.length):"normal";const d=transformCandidate(id,demoResult(id,variant),variant);if(id==="blue_opening")state.decisionBoundary=buildDecisionBoundary(d);state.results[id]=d;results[id]=validateFullResult(id,d,variant);}const valid=Object.values(results).every(x=>x.valid);state=old;renderAll();return {valid,results};};
