function legacyScoreBasis(v){return v==="insufficient_information"?v:v==="explicit_user_input"||v==="externally_verified"?v:"model_judgment";}
function migrateState(input,source="unknown"){
  const original=clone(input||{}),next=freshState();next.id=original.id||next.id;next.createdAt=original.createdAt||next.createdAt;next.updatedAt=original.updatedAt||next.updatedAt;next.input={...next.input,...(original.input||{})};next.deterministic=extractDeterministicInput(next.input);
  next.meta={...next.meta,...(original.meta||{}),important:arr(original.meta?.important),excluded:arr(original.meta?.excluded),edited:arr(original.meta?.edited),stale:arr(original.meta?.stale)};
  if(next.meta.status==="running"||next.meta.currentHat){next.meta.interruptedHat=next.meta.currentHat||original.meta?.interruptedHat||null;next.meta.currentHat=null;next.meta.status="interrupted";}
  const legacySchema=Number(original.schemaVersion||original.build?.schemaVersion||1);const results=original.results||{};
  if(legacySchema>=3){
    next.build={...BUILD,...(original.build||{}),appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION};next.appVersion=APP_VERSION;next.schemaVersion=SCHEMA_VERSION;
    next.deterministic=original.deterministic?clone(original.deterministic):extractDeterministicInput(next.input);
    next.decisionBoundary=original.decisionBoundary?clone(original.decisionBoundary):(results.blue_opening?buildDecisionBoundary(results.blue_opening):{criteria:[],outOfScope:[]});
    next.results=clone(results);next.resultMeta=Object.fromEntries(HAT_IDS.map(id=>{const m={...freshResultMeta(),...(original.resultMeta?.[id]||{})};m.validation={...emptyValidation(),...(m.validation||{}),warnings:normalizeWarnings(m.validation?.warnings,id)};return [id,m];}));
    for(const id of HAT_IDS){if(!next.results[id])continue;const variant=next.resultMeta[id]?.schemaVariant||(id==="red"?selectRedSchemaVariant(next.deterministic.stakeholders.length):"normal");const v=validateFullResult(id,next.results[id],variant,next);next.resultMeta[id].validation=v;if(!v.valid)next.resultMeta[id].status="invalid";}
    next.runSummary=clone(original.runSummary||null);next.test=clone(original.test||null);debugLog("legacy-migration",{source,legacy:false,fromSchema:legacySchema,meetingId:next.id});return next;
  }
  for(const id of HAT_IDS){if(!results[id])continue;let r=clone(results[id]);let variant="normal";
    if(id==="blue_opening")r={reframedTopic:r.reframedTopic||"",coreQuestion:r.coreQuestion||"",decisionCriteria:arr(r.decisionCriteria),assumptions:arr(r.assumptions),discussionPoints:arr(r.discussionPoints),outOfScope:arr(r.outOfScope),ambiguities:arr(r.ambiguities)};
    if(id==="white"){
      r={inputFacts:next.deterministic.inputClaims,generalObservations:arr(r.generalObservations),assumptions:arr(r.assumptions).map(x=>typeof x==="string"?{text:x,relationToInput:"unknown",reason:"旧版データから移行"}:{text:x.text||"",relationToInput:x.relationToInput||((x.conflictsWithInput)?"possible_conflict":"unknown"),reason:x.reason||"旧版データから移行"}),missingInformation:arr(r.missingInformation).map(x=>typeof x==="string"?{text:x,priority:"medium",reason:"旧版データから移行"}:x),researchQuestions:arr(r.researchQuestions),numbers:arr(r.numbers).map(x=>({label:x.label||"数値",value:String(x.value??"不明"),provenance:x.provenance||((x.status==="user_input")?"user_input":"unknown")}))};
    }
    if(id==="red"){
      variant=selectRedSchemaVariant(next.deterministic.stakeholders.length);const byName=new Map(next.deterministic.stakeholders.map(x=>[normalizeText(x.name),x.id]));const old=arr(r.stakeholders);const converted=old.map((x,i)=>{const sid=x.stakeholderId||byName.get(normalizeText(x.name))||next.deterministic.stakeholders[i]?.id;if(!sid)return null;if(variant==="normal")return {stakeholderId:sid,positiveFeeling:arr(x.positiveFeelings)[0]||x.positiveFeeling||"期待を確認する必要がある。",negativeFeeling:arr(x.negativeFeelings)[0]||x.negativeFeeling||"不安を確認する必要がある。",intuitiveReaction:x.intuitiveReaction||"反応は未確認。",communicationConcern:x.communicationConcern||"説明方法を確認する。"};return {stakeholderId:sid,emotionalTone:x.emotionalTone||"unknown",mainConcern:x.mainConcern||arr(x.negativeFeelings)[0]||"主要懸念は未確認。",intuitiveReaction:x.intuitiveReaction||"反応は未確認。",communicationConcern:x.communicationConcern||"説明方法を確認する。"};}).filter(Boolean).slice(0,variant==="core"?6:10);r={stakeholders:converted,hiddenEmotions:arr(r.hiddenEmotions).slice(0,3),consensusConcerns:arr(r.consensusConcerns).slice(0,4)};if(variant==="core"){const remaining=next.deterministic.stakeholders.slice(6);r.otherStakeholdersSummary={coveredStakeholderIds:remaining.map(x=>x.id),commonReaction:"旧版では個別情報を保持していません。",mainCommunicationNeed:"関係者別に再確認してください。"};}r.schemaVariant=variant;
    }
    if(id==="black"){r={...r,risks:arr(r.risks).filter(x=>!PLACEHOLDERS.has(x?.name)).map(x=>({...x,likelihood:Number.isInteger(x.likelihood)?x.likelihood:0,impact:Number.isInteger(x.impact)?x.impact:0,scoreBasis:legacyScoreBasis(x.scoreBasis),warningSigns:arr(x.warningSigns),mitigations:arr(x.mitigations).length?x.mitigations:arr(x.mitigation),residualRiskLevel:Number.isInteger(x.residualRiskLevel)?x.residualRiskLevel:0,residualRiskNote:x.residualRiskNote||x.residualRisk||""})),fatalConditions:arr(r.fatalConditions)};}
    if(id==="yellow")r={...r,benefits:arr(r.benefits).filter(x=>!PLACEHOLDERS.has(x?.name)).map(x=>({...x,beneficiaries:arr(x.beneficiaries).length?x.beneficiaries:["未特定"],conditions:arr(x.conditions),indicators:arr(x.indicators),evidenceLevel:x.evidenceLevel==="speculative"?"speculative":"general_inference"})),strategicOpportunities:arr(r.strategicOpportunities)};
    if(id==="green"){const constraints=next.deterministic.constraints.slice(0,4),outs=next.decisionBoundary.outOfScope.slice(0,4);r={ideas:arr(r.ideas).filter(x=>!PLACEHOLDERS.has(x?.name)).slice(0,4).map((x,i)=>({ideaId:`G-${String(i+1).padStart(3,"0")}`,name:x.name||`案${i+1}`,category:x.category||"other",description:x.description||"",distinctiveFeature:x.distinctiveFeature||x.novelty||"",benefits:arr(x.benefits).slice(0,2),challenges:arr(x.challenges).slice(0,2),requirements:arr(x.requirements).slice(0,3),pilotMethod:x.pilotMethod||"",constraintAssessments:constraints.map(c=>({constraintId:c.id,status:"unknown",note:"旧版から移行"})),outOfScopeAssessments:outs.map(o=>({outOfScopeId:o.id,status:"unknown",note:"旧版から移行"}))})),combinationIdeas:arr(r.combinationIdeas).slice(0,2)};while(r.ideas.length<4)r.ideas.push({ideaId:`G-${String(r.ideas.length+1).padStart(3,"0")}`,name:`再生成が必要な案${r.ideas.length+1}`,category:"other",description:"旧版データでは案が不足しています。",distinctiveFeature:"再生成してください。",benefits:["未評価"],challenges:["情報不足"],requirements:[],pilotMethod:"",constraintAssessments:constraints.map(c=>({constraintId:c.id,status:"unknown",note:"旧版から移行"})),outOfScopeAssessments:outs.map(o=>({outOfScopeId:o.id,status:"unknown",note:"旧版から移行"}))});}
    if(id==="blue_closing"){const options=arr(r.options).filter(x=>!PLACEHOLDERS.has(x?.name)).slice(0,3).map((x,i)=>({optionId:`OPT-${String(i+1).padStart(3,"0")}`,sourceType:"new_synthesis",sourceIdeaIds:[],label:x.label||x.name||`案${i+1}`,summary:x.summary||x.description||"",advantages:arr(x.advantages).slice(0,2),risks:arr(x.risks).slice(0,2),feasibility:Number.isInteger(x.feasibility)?x.feasibility:0,recommendationScore:Number.isInteger(x.recommendationScore)?x.recommendationScore:0,scoreBasis:legacyScoreBasis(x.scoreBasis)}));while(options.length<2)options.push({optionId:`OPT-${String(options.length+1).padStart(3,"0")}`,sourceType:"baseline",sourceIdeaIds:[],label:`比較案${options.length+1}`,summary:"旧版データでは比較案が不足しています。",advantages:["未評価"],risks:["情報不足"],feasibility:0,recommendationScore:0,scoreBasis:"insufficient_information"});r={executiveSummary:r.executiveSummary||"",recommendation:{type:["proceed","conditional","pilot","research","hold","compare"].includes(r.recommendation?.type)?r.recommendation.type:"compare",label:r.recommendation?.label||"比較を継続",rationale:r.recommendation?.rationale||"旧版データから移行",optionId:options[0].optionId},keyReasons:arr(r.keyReasons).slice(0,4),options,keyRisks:arr(r.keyRisks).slice(0,4),successConditions:arr(r.successConditions).slice(0,4),nextActions:arr(r.nextActions).filter(x=>!/[0-9]+/.test(String(x?.action||""))).slice(0,4).map((x,i)=>({order:i+1,action:x.action||"確認する",purpose:x.purpose||"旧版データの確認"})),missingInformation:arr(r.missingInformation).slice(0,5),caveats:arr(r.caveats).slice(0,4),informationCompleteness:Number(r.informationCompleteness)||0};}
    if(id==="blue_opening")next.decisionBoundary=buildDecisionBoundary(r);
    next.results[id]=r;const m=clone(original.resultMeta?.[id]||freshResultMeta());m.schemaVariant=m.schemaVariant||variant;m.validation=m.validation||emptyValidation();m.validation.warnings=normalizeWarnings(m.validation.warnings,id);m.status=m.status||"warning";m.sourceResultVersion=SCHEMA_VERSION;next.resultMeta[id]={...freshResultMeta(),...m};
    const val=validateFullResult(id,r,next.resultMeta[id].schemaVariant||"normal",next);if(!val.valid){next.resultMeta[id].status="invalid";next.resultMeta[id].validation=val;}else if(legacySchema<3){next.resultMeta[id].status="warning";next.resultMeta[id].validation={...val,warnings:[...val.warnings,createWarning("MIGRATED_LEGACY_DATA","review_required","旧版データから移行しました。内容を確認してください。",id)]};}
  }
  next.build={...BUILD,...(original.build||{}),appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION};next.appVersion=APP_VERSION;next.schemaVersion=SCHEMA_VERSION;next.runSummary=original.runSummary||null;next.test=original.test||null;debugLog("legacy-migration",{source,legacy:legacySchema<3,fromSchema:legacySchema,meetingId:next.id});return next;
}
function migrateStoredMeetings(){try{if(storage.getItem(MIGRATION_MARKER_KEY))return;const raw=storage.getItem(STORAGE_KEY);if(!raw){storage.setItem(MIGRATION_MARKER_KEY,now());return;}storage.setItem(BACKUP_KEY,raw);const all=JSON.parse(raw),migrated={};for(const [id,x] of Object.entries(all))migrated[id]=migrateState(x,"storage");storage.setItem(STORAGE_KEY,JSON.stringify(migrated));storage.setItem(MIGRATION_MARKER_KEY,now());}catch(e){debugLog("storage-migration-error",{error:errorData(e)});}}

function openEdit(id){editingHat=id;$("#editTitle").textContent=`${HATS.find(x=>x.id===id)?.name}を編集`;$("#editJson").value=JSON.stringify(state.results[id],null,2);$("#editError").classList.add("hidden");$("#editDialog").showModal();}
async function saveEdit(){try{const data=JSON.parse($("#editJson").value),variant=state.resultMeta[editingHat]?.schemaVariant||"normal",v=validateFullResult(editingHat,data,variant);if(!v.valid)throw new Error(v.errors.join("\n"));state.results[editingHat]=data;state.resultMeta[editingHat].validation=v;state.resultMeta[editingHat].status=v.warnings.length?"warning":"valid";state.resultMeta[editingHat].formatUsed="manual";state.resultMeta[editingHat].updatedAt=now();state.meta.edited=unique([...state.meta.edited,editingHat]);if(editingHat==="blue_opening")state.decisionBoundary=buildDecisionBoundary(data);markDependentsStale(editingHat,true);$("#editDialog").close();renderAll();await queueAutosave("manual-edit");}catch(e){$("#editError").textContent=e.message;$("#editError").classList.remove("hidden");}}
function openResultDetails(id){detailHat=id;const m=state.resultMeta[id],h=HATS.find(x=>x.id===id);$("#resultDetailTitle").textContent=`${h.name}：生成・検証の詳細`;$("#resultDetailSummary").innerHTML=`<div class="miniGrid"><div class="subcard"><strong>状態</strong><br>${esc(formatStatus(m.status))}</div><div class="subcard"><strong>Schema</strong><br>${esc(m.schemaVariant||"—")}</div><div class="subcard"><strong>試行回数</strong><br>${m.generation?.attemptCount||0}</div><div class="subcard"><strong>生成時間</strong><br>${esc(formatElapsed(m.generation?.durationMs||0))}</div></div>${warningHtml(m.validation?.warnings)}${m.validation?.errors?.length?`<div class="notice error">${m.validation.errors.map(esc).join("<br>")}</div>`:""}`;$("#resultDetailRaw").value=m.rawOutput||"";$("#resultDetailNormalized").value=m.normalizedOutput||JSON.stringify(state.results[id],null,2);$("#resultDetailDialog").showModal();}

function openResumeDialog(){$("#resumeDialog").showModal();}
function openNewMeetingDialog(){$("#newMeetingDialog").showModal();}
function openWarningDialog(id,next){const warnings=state.resultMeta[id]?.validation?.warnings||[];$("#warningDialogTitle").textContent=`${HATS.find(x=>x.id===id)?.short}で確認が必要です`;$("#warningDialogBody").innerHTML=warningHtml(warnings);$("#warningContinueBtn").dataset.next=next||"";$("#warningContinueBtn").dataset.hat=id;$("#warningDialog").showModal();}
async function continueAfterWarning(){const id=$("#warningContinueBtn").dataset.hat,next=$("#warningContinueBtn").dataset.next;for(const w of arr(state.resultMeta[id]?.validation?.warnings))w.acknowledged=true;state.resultMeta[id].userAcceptedWarnings=true;$("#warningDialog").close();if(!next)return;if(state.runSummary)state.runSummary.status="running";await runWorkflowFrom(next);}

function detectImportType(x){if(x?.testType||x?.testCaseId&&x?.expected)return "test";if(x?.input&&x?.results)return "meeting";throw new Error("対応する会議・テストデータではありません");}
function importState(file){const fr=new FileReader();fr.onload=()=>{try{const x=JSON.parse(fr.result);const type=detectImportType(x);if(DEV_MODE||type==="test"){pendingImportData=x;openImportModeDialog(type);}else{state=migrateState(x,"import");currentRunId=state.runSummary?.runId||null;syncInputs();renderAll();$("#exportDialog").close();}}catch(e){showGlobalNotice(`読み込み失敗：${e.message}`,"error");}};fr.readAsText(file);}
function openImportModeDialog(type){$("#importModeMessage").textContent=type==="test"?"テストケースをどのモードで実行しますか。":"読み込んだ会議データの扱いを選択してください。";$("#importModeDialog").showModal();}
function runImportMode(mode){const x=pendingImportData;pendingImportData=null;$("#importModeDialog").close();if(mode==="display"){state=migrateState(x,"display-test");state.test={testType:"display",testCaseId:x.testCaseId||`display-${state.id}`,expected:x.expected||null};currentRunId=null;syncInputs();renderAll();currentTestReport=runTestAssertions(state.test);showTestReport(currentTestReport);}if(mode==="migration"){const migrated=migrateState(x,"migration-test");currentTestReport={testCaseId:x.testCaseId||`migration-${migrated.id}`,testType:"migration",generatedAt:now(),summary:{status:migrated.schemaVersion===3?"PASS":"FAIL"},assertions:[{id:"migration_status",label:"Schema 3へ移行",status:migrated.schemaVersion===3?"PASS":"FAIL",actual:migrated.schemaVersion,expected:3}],before:{schemaVersion:x.schemaVersion||x.build?.schemaVersion||1},after:{schemaVersion:migrated.schemaVersion,invalidHats:HAT_IDS.filter(id=>migrated.resultMeta[id]?.status==="invalid")}};state=migrated;syncInputs();renderAll();showTestReport(currentTestReport);}if(mode==="generation"){const base=x.input?x:migrateState(x,"generation-test");state=freshState();state.input={...state.input,...base.input};state.test={testType:"generation",testCaseId:x.testCaseId||`generation-${uuid()}`,expected:x.expected||{completedHats:7,maxRetries:1,allowedBlockingWarnings:0}};syncInputs();renderAll();startFreshWorkflow();}}
