function runTestAssertions(test=state.test){const exp=test?.expected||{},assertions=[];const add=(id,labelText,pass,actual,expected)=>assertions.push({id,label:labelText,status:pass?"PASS":"FAIL",actual,expected});const completed=completedCount();add("completed_hats","7帽子完了",completed===(exp.completedHats??7),completed,exp.completedHats??7);const invalid=HAT_IDS.filter(id=>state.resultMeta[id]?.status==="invalid");add("schema_valid","JSON Schema検証",invalid.length===0,invalid,"なし");if(exp.maxRetries!=null)add("max_retries","再試行回数",(state.runSummary?.retryCount||0)<=exp.maxRetries,state.runSummary?.retryCount||0,exp.maxRetries);if(exp.requiredStakeholders){const red=state.results.red||{};const ids=[...arr(red.stakeholders).map(x=>x.stakeholderId),...arr(red.otherStakeholdersSummary?.coveredStakeholderIds)];const names=ids.map(stakeholderName);const missing=exp.requiredStakeholders.filter(x=>!names.some(n=>normalizeText(n).includes(normalizeText(x))||normalizeText(x).includes(normalizeText(n))));add("required_stakeholders","必要関係者の網羅",missing.length===0,missing,"なし");}if(exp.forbiddenConcepts){const downstream=JSON.stringify({green:state.results.green,blue_closing:state.results.blue_closing});const hits=exp.forbiddenConcepts.filter(x=>downstream.includes(x));add("forbidden_concepts","禁止概念の不在",hits.length===0,hits,"なし");}if(exp.maxTotalDurationMs!=null){const ms=state.runSummary?.completedAt&&state.runSummary?.startedAt?new Date(state.runSummary.completedAt)-new Date(state.runSummary.startedAt):0;add("max_duration","最大実行時間",ms<=exp.maxTotalDurationMs,ms,exp.maxTotalDurationMs);}const blocking=warningCounts().blocking;add("blocking_warning_count","停止警告",blocking<=(exp.allowedBlockingWarnings??0),blocking,exp.allowedBlockingWarnings??0);return {testCaseId:test?.testCaseId||"ad-hoc",testType:test?.testType||"generation",build:state.build,runSummary:state.runSummary,generatedAt:now(),summary:{status:assertions.every(x=>x.status==="PASS")?"PASS":"FAIL"},assertions};}
function completeGenerationTest(){currentTestReport=runTestAssertions(state.test);debugLog("test-complete",{report:currentTestReport});showTestReport(currentTestReport);}
function showTestReport(report){$("#testReportBody").innerHTML=`<div class="recommend"><strong>総合：${esc(report.summary.status)}</strong><p>${esc(report.testCaseId)}</p></div><table class="optionTable"><thead><tr><th>項目</th><th>判定</th><th>実際</th><th>期待</th></tr></thead><tbody>${report.assertions.map(x=>`<tr><td>${esc(x.label)}</td><td><strong>${esc(x.status)}</strong></td><td>${esc(JSON.stringify(x.actual))}</td><td>${esc(JSON.stringify(x.expected))}</td></tr>`).join("")}</tbody></table>`;$("#testReportDialog").showModal();}
function testReportMarkdown(report){return `# 6色思考会議 テストレポート\n\n- テストケース: ${report.testCaseId}\n- 種別: ${report.testType}\n- 総合: ${report.summary.status}\n- 生成日時: ${report.generatedAt}\n\n${report.assertions.map(x=>`- ${x.status}：${x.label}（実際: ${JSON.stringify(x.actual)} / 期待: ${JSON.stringify(x.expected)}）`).join("\n")}\n`;}

function demoResult(id,variant="normal"){
  const stakeholders=state.deterministic.stakeholders.length?state.deterministic.stakeholders:[{id:"S-001",name:"意思決定者"},{id:"S-002",name:"現場担当者"},{id:"S-003",name:"利用者"}];
  const demo={
    blue_opening:{reframedTopic:`${state.input.topic||"この議題"}について、実施可否と条件を判断する`,coreQuestion:"期待効果が主要な制約とリスクを上回り、現実的な実施方法を構築できるか",decisionCriteria:state.deterministic.focusItems.length?state.deterministic.focusItems.slice(0,6):["効果","コスト","実現性","関係者受容性"],assumptions:["入力された背景を現時点の前提とする"],discussionPoints:["現状維持の課題","導入による効果","実施体制と費用"],outOfScope:["入力にない法令適合性の断定"],ambiguities:["費用水準と期限の詳細"]},
    white:{generalObservations:["新制度の導入では運用負荷と期待効果を比較する必要がある"],assumptions:[{text:"関係者との調整が必要になる",relationToInput:"supplements",reason:"一般的な実施条件"}],missingInformation:[{text:"現状コスト",priority:"high",reason:"導入前後の比較に必要"},{text:"対象量・需要量",priority:"high",reason:"運用規模の判断に必要"}],researchQuestions:["現状と導入後の費用差はどれくらいか"],numbers:[]},
    black:{summary:"最大のリスクは、効果を確認しないまま運用負荷だけが固定化すること。",risks:[{name:"実施負荷の過小評価",cause:"現場条件と必要資源の把握不足",likelihood:3,impact:4,scoreBasis:"model_judgment",warningSigns:["準備作業の遅延"],mitigations:["小規模試行"],residualRiskLevel:3,residualRiskNote:"長期負荷が残る"},{name:"合意不足",cause:"便益と負担の説明不足",likelihood:3,impact:4,scoreBasis:"model_judgment",warningSigns:["同じ懸念が反復"],mitigations:["関係者別説明"],residualRiskLevel:3,residualRiskNote:"価値観の対立が残る"}],fatalConditions:["必須条件を満たせない場合"]},
    yellow:{summary:"段階導入により改善効果と学習効果を得られる可能性がある。",benefits:[{name:"現状課題の改善",description:"現行制度の課題を縮小できる可能性がある",timeframe:"medium",beneficiaries:["利用者"],conditions:["効果指標を設定する"],indicators:["コスト"],evidenceLevel:"general_inference"},{name:"判断精度向上",description:"試行データで本格導入判断を改善できる",timeframe:"short",beneficiaries:["意思決定者"],conditions:["結果を記録する"],indicators:["不足情報解消数"],evidenceLevel:"general_inference"}],strategicOpportunities:["共同化"]}
  };
  if(id==="red"){
    const target=(variant==="core"||(variant==="compact"&&stakeholders.length>10))?stakeholders.slice(0,6):stakeholders;let rows;if(variant==="normal")rows=target.map(x=>({stakeholderId:x.id,positiveFeeling:"改善への期待。",negativeFeeling:"負担増への不安。",intuitiveReaction:"必要性は感じるが、具体的負担が見えないと慎重になる。",communicationConcern:"負担と便益を説明する。"}));else if(variant==="compact")rows=target.map(x=>({stakeholderId:x.id,mainConcern:"負担の増加。",intuitiveReaction:"期待と不安が混在する。",communicationNeed:"適用条件を明示する。"}));else rows=target.map(x=>({stakeholderId:x.id,emotionalTone:"mixed",mainConcern:"負担の増加。",intuitiveReaction:"期待と不安が混在する。",communicationConcern:"適用条件を明示する。"}));const out={stakeholders:rows,consensusConcerns:["負担と便益の分配"]};if(variant!=="compact")out.hiddenEmotions=["変化への抵抗"];if(variant==="core"){const rem=stakeholders.slice(6);out.otherStakeholdersSummary={coveredStakeholderIds:rem.map(x=>x.id),commonReaction:"目的には理解を示すが負担を懸念する。",mainCommunicationNeed:"役割と負担を明示する。"};}return out;
  }
  if(id==="green"){const count=variant==="compact"?3:4,cids=state.deterministic.constraints.slice(0,4),oids=state.decisionBoundary.outOfScope.slice(0,4);return {ideas:Array.from({length:count},(_,i)=>({ideaId:`G-${String(i+1).padStart(3,"0")}`,name:["限定実証","段階導入","共同実施","外部委託"][i]||`案${i+1}`,category:["pilot","phased","joint","outsourcing"][i]||"other",description:"対象を限定し、費用と効果を計測する。",distinctiveFeature:"全面導入前に実測する。",benefits:["初期リスクを抑える"],challenges:["評価設計が必要"],requirements:["責任者の設定"],pilotMethod:"3か月試行する。",constraintAssessments:cids.map(c=>({constraintId:c.id,status:"unknown",note:"要確認"})),outOfScopeAssessments:oids.map(o=>({outOfScopeId:o.id,status:"not_related",note:""}))})),combinationIdeas:["限定実証後に段階拡大する"]};}
  if(id==="blue_closing"){const count=variant==="compact"?2:3,ideas=state.results.green?.ideas||[];const options=Array.from({length:count},(_,i)=>({optionId:`OPT-${String(i+1).padStart(3,"0")}`,sourceType:i<ideas.length?"green_idea":"baseline",sourceIdeaIds:i<ideas.length?[ideas[i].ideaId]:[],label:ideas[i]?.name||["現状維持","追加調査"][i]||`案${i+1}`,summary:ideas[i]?.description||"現状を維持しながら情報を集める。",advantages:["不確実性を抑える"],risks:["効果発現が遅い"],feasibility:4-i,recommendationScore:i===0?5:3,scoreBasis:"model_judgment"}));return {executiveSummary:"小規模試行から始め、結果に基づき本格判断する案が妥当です。",recommendation:{type:"pilot",label:"試行後に本格判断",rationale:"不確実性を実測で低減できるため。",optionId:options[0].optionId},keyReasons:["効果と負担を実測できる","重大リスクを限定できる"],options,keyRisks:["試行結果が再現しない可能性"],successConditions:["判断基準を事前設定する"],nextActions:[{order:1,action:"不足情報を整理する",purpose:"試行設計の前提を整える"},{order:2,action:"小規模試行を設計する",purpose:"費用と効果を測定する"}],missingInformation:["実施費用"],caveats:["重要な数値は外部確認する"]};}
  return demo[id];
}

function injectDeveloperPanel(){if(!DEV_MODE)return;const panel=document.createElement("section");panel.className="panel devPanel";panel.innerHTML=`<h2>開発者モード</h2><p>表示・移行・生成テストを実行し、PASS／FAILレポートを作成します。</p><div class="actions"><label class="btn">テストJSONを選択<input type="file" id="devTestFile" accept="application/json,.json" hidden></label><button class="btn" id="showCurrentTestReport">現在のテスト判定</button></div>`;$("#inputPanel").after(panel);$("#devTestFile").onchange=e=>e.target.files[0]&&importState(e.target.files[0]);$("#showCurrentTestReport").onclick=()=>{currentTestReport=runTestAssertions(state.test||{testCaseId:"current-state",testType:"display",expected:{completedHats:7,allowedBlockingWarnings:0}});showTestReport(currentTestReport);};}
