function formatStatus(status){return {idle:"未実行",generating:"実行中",valid:"完了",warning:"要確認",invalid:"無効",stale:"再生成推奨",interrupted:"中断"}[status]||status;}
function formatPhase(p){return {preparing_session:"セッションを準備しています",measuring_context:"入力サイズを確認しています",generating:"Gemini Nanoが検討しています",receiving:"構造化結果を受信しました",validating_schema:"JSON構造を検証しています",validating_semantics:"内容の整合性を確認しています",saving:"結果を保存しています",awaiting_review:"確認が必要な項目があります",complete:"完了しました",retrying_compact:"出力を短縮して再試行しています"}[p]||"";}
function completedCount(){return HAT_IDS.filter(id=>state.results[id]&&!["invalid","stale","interrupted"].includes(state.resultMeta[id]?.status)).length;}
function updateTitle(){const t=state.input.topic?.trim()||"新しい会議";$("#meetingTitle").textContent=t;if(!document.hidden&&!state.meta.currentHat)document.title="6色思考会議 — Gemini Nano";}
function renderSidebar(){
  const steps=HATS.map(h=>{const m=state.resultMeta[h.id]||freshResultMeta();const cls=m.status==="generating"?"active":m.status==="valid"?"done":m.status==="warning"?"warning":m.status==="invalid"||m.status==="interrupted"?"invalid":m.status==="stale"?"stale":"";return `<div class="step ${cls}"><span class="dot"></span><div><strong>${esc(h.short)}</strong><div>${esc(formatStatus(m.status))}</div></div></div>`;}).join("");
  const run=state.runSummary?.runId?safeText(state.runSummary.runId,8):"—";
  $("#sidebar").innerHTML=steps+`<div class="sideMeta"><div class="statusPill ${ai.status==="available"?"ok":ai.status==="downloadable"?"warn":"bad"}"><i></i><span>${esc(ai.label)}</span></div><p>${completedCount()} / 7 完了</p><p>保存：${esc(state.meta.autosaveStatus||"未保存")}</p><p>Run：${esc(run)}</p><p>v${esc(APP_VERSION)} / Schema ${SCHEMA_VERSION}</p></div>`;
  updateAIPill();
}
function warningHtml(warnings){if(!arr(warnings).length)return "";return arr(warnings).map(w=>`<div class="notice warning-${esc(w.severity)}"><strong>${w.severity==="blocking"?"⛔":w.severity==="review_required"?"⚠":"ℹ"} ${esc(label(w.severity))}</strong><div>${esc(w.message)}</div></div>`).join("");}
function list(title,items){const a=arr(items);return a.length?`<div class="section"><h3>${esc(title)}</h3><ul class="list">${a.map(x=>`<li>${esc(typeof x==="string"?x:JSON.stringify(x))}</li>`).join("")}</ul></div>`:"";}
function textBlock(title,value){return value?`<div class="section"><h3>${esc(title)}</h3><p>${esc(value)}</p></div>`:"";}
function chips(title,items){const a=arr(items);return a.length?`<div class="section"><h3>${esc(title)}</h3><div class="chips">${a.map(x=>`<span class="chip">${esc(x)}</span>`).join("")}</div></div>`:"";}
function stakeholderName(id){return findStakeholder(id)?.name||id;}
function renderResult(id,r){
  if(id==="blue_opening")return textBlock("議題の再構成",r.reframedTopic)+textBlock("中心的な問い",r.coreQuestion)+chips("判断基準",r.decisionCriteria)+list("前提",r.assumptions)+list("主な論点",r.discussionPoints)+list("対象外",r.outOfScope)+list("曖昧な点",r.ambiguities);
  if(id==="white")return (arr(r.inputFacts).length?`<div class="section"><h3>ユーザー入力の事実</h3>${r.inputFacts.map(x=>`<div class="subcard"><strong>${esc(x.id)}</strong> ${esc(x.text)}<div class="sourceLine"><span class="metaBadge">${esc(label(x.sourceField))}</span><span class="metaBadge">${esc(label(x.verificationStatus))}</span></div></div>`).join("")}</div>`:"")+list("一般的な観察",r.generalObservations)+(arr(r.assumptions).length?`<div class="section"><h3>追加仮定</h3>${r.assumptions.map(x=>`<div class="subcard"><strong>${esc(label(x.relationToInput))}</strong><p>${esc(x.text)}</p>${x.reason?`<small>${esc(x.reason)}</small>`:""}</div>`).join("")}</div>`:"")+(arr(r.missingInformation).length?`<div class="section"><h3>不足情報</h3>${r.missingInformation.map(x=>`<div class="subcard"><strong>優先度 ${esc(PRIORITY_LABELS[x.priority]||x.priority)}</strong><p>${esc(x.text)}</p><small>${esc(x.reason)}</small></div>`).join("")}</div>`:"")+list("調査質問",r.researchQuestions)+(arr(r.numbers).length?`<div class="section"><h3>数値</h3>${r.numbers.map(x=>`<div class="subcard"><strong>${esc(x.label)}：${esc(x.value)}</strong><div class="sourceLine"><span class="metaBadge">${esc(label(x.provenance))}</span></div></div>`).join("")}</div>`:"");
  if(id==="red")return (arr(r.stakeholders).length?`<div class="section"><h3>関係者別の反応</h3>${r.stakeholders.map(x=>`<div class="subcard"><h4>${esc(stakeholderName(x.stakeholderId))} <span class="metaBadge">${esc(x.stakeholderId)}</span>${x.emotionalTone?` <span class="score">${esc(label(x.emotionalTone))}</span>`:""}</h4>${textBlock("肯定的な感情",x.positiveFeeling)}${textBlock("否定的な感情",x.negativeFeeling)}${textBlock("主要懸念",x.mainConcern)}${textBlock("直感的反応",x.intuitiveReaction)}${textBlock("伝達上の注意",x.communicationConcern||x.communicationNeed)}</div>`).join("")}</div>`:"")+(r.otherStakeholdersSummary?`<div class="subcard"><h4>その他の関係者（${r.otherStakeholdersSummary.coveredStakeholderIds.length}件）</h4>${textBlock("共通反応",r.otherStakeholdersSummary.commonReaction)}${textBlock("伝達上の必要",r.otherStakeholdersSummary.mainCommunicationNeed)}<small>${r.otherStakeholdersSummary.coveredStakeholderIds.map(stakeholderName).map(esc).join("、")}</small></div>`:"")+list("表面化しにくい感情",r.hiddenEmotions)+list("合意形成上の注意",r.consensusConcerns);
  if(id==="black")return textBlock("要約",r.summary)+(arr(r.risks).length?`<div class="section"><h3>主要リスク</h3>${r.risks.map(x=>`<div class="subcard"><h4>${esc(x.name)} <span class="score">可能性 ${scoreDisplay(x.likelihood)}</span> <span class="score">影響 ${scoreDisplay(x.impact)}</span> <span class="score">リスク値 ${x.likelihood>0&&x.impact>0?x.likelihood*x.impact:"未評価"}</span></h4>${textBlock("原因",x.cause)}<div class="sourceLine"><span class="metaBadge">${esc(label(x.scoreBasis))}</span></div>${list("早期兆候",x.warningSigns)}${list("対応策",x.mitigations)}${textBlock("残余リスク",`${scoreText(x.residualRiskLevel)}${x.residualRiskNote?`：${x.residualRiskNote}`:""}`)}</div>`).join("")}</div>`:"")+list("致命的となる条件",r.fatalConditions);
  if(id==="yellow")return textBlock("要約",r.summary)+(arr(r.benefits).length?`<div class="section"><h3>利点</h3>${r.benefits.map(x=>`<div class="subcard"><h4>${esc(x.name)} <span class="score">${esc(label(x.timeframe))}</span> <span class="score">${esc(label(x.evidenceLevel))}</span></h4>${textBlock("説明",x.description)}${list("受益者",x.beneficiaries)}${list("成立条件",x.conditions)}${list("評価指標",x.indicators)}</div>`).join("")}</div>`:"")+list("戦略的な機会",r.strategicOpportunities);
  if(id==="green")return (arr(r.ideas).length?`<div class="section"><h3>代替案</h3>${r.ideas.map(x=>`<div class="subcard"><h4>${esc(x.name)} <span class="metaBadge">${esc(x.ideaId)}</span> <span class="score">${esc(CATEGORY_LABELS[x.category]||x.category)}</span></h4>${textBlock("概要",x.description)}${textBlock("特徴",x.distinctiveFeature)}${list("利点",x.benefits)}${list("課題",x.challenges)}${list("必要条件",x.requirements)}${textBlock("実証方法",x.pilotMethod)}${renderAssessments(x)}</div>`).join("")}</div>`:"")+list("組合せ案",r.combinationIdeas);
  if(id==="blue_closing")return `<div class="recommend"><strong>${esc(r.recommendation?.label||label(r.recommendation?.type)||"推奨判断")}</strong><p>${esc(r.recommendation?.rationale||"")}</p></div>${textBlock("エグゼクティブサマリー",r.executiveSummary)}${list("判断理由",r.keyReasons)}${arr(r.options).length?`<div class="section"><h3>選択肢比較</h3><table class="optionTable"><thead><tr><th>案</th><th>概要</th><th>利点</th><th>リスク</th><th>実現性</th><th>推奨度</th></tr></thead><tbody>${r.options.map(o=>`<tr><td><strong>${esc(o.label)}</strong><br><span class="metaBadge">${esc(o.optionId)}</span> <span class="metaBadge">${esc(label(o.scoreBasis))}</span>${o.sourceIdeaIds.length?`<br><small>${o.sourceIdeaIds.map(esc).join("、")}</small>`:""}</td><td>${esc(o.summary)}</td><td>${arr(o.advantages).map(esc).join("<br>")}</td><td>${arr(o.risks).map(esc).join("<br>")}</td><td>${scoreDisplay(o.feasibility)}</td><td>${scoreDisplay(o.recommendationScore)}</td></tr>`).join("")}</tbody></table></div>`:""}${list("主要リスク",r.keyRisks)}${list("成功条件",r.successConditions)}${arr(r.nextActions).length?`<div class="section"><h3>次のアクション</h3><ol>${[...r.nextActions].sort((a,b)=>a.order-b.order).map(a=>`<li><strong>${esc(a.action)}</strong><br><span class="hatState">${esc(a.purpose)}</span></li>`).join("")}</ol></div>`:""}${list("不足情報",r.missingInformation)}${list("留意事項",r.caveats)}<div class="section"><h3>情報充足度（ハーネス計算）</h3><div class="meter"><span style="width:${Math.max(0,Math.min(100,Number(r.informationCompleteness)||0))}%"></span></div><p>${esc(r.informationCompleteness)} / 100</p></div>`;
  return `<pre>${esc(JSON.stringify(r,null,2))}</pre>`;
}
function renderAssessments(idea){const cs=arr(idea.constraintAssessments),os=arr(idea.outOfScopeAssessments);return (cs.length?`<div class="section"><h3>制約評価</h3>${cs.map(x=>`<div class="sourceLine"><span class="metaBadge ${x.status==="violates"?"invalid":""}">${esc(x.constraintId)}：${esc(label(x.status))}</span><small>${esc(x.note||"")}</small></div>`).join("")}</div>`:"")+(os.length?`<div class="section"><h3>対象外評価</h3>${os.map(x=>`<div class="sourceLine"><span class="metaBadge ${x.status==="conflicts"?"invalid":""}">${esc(x.outOfScopeId)}：${esc(label(x.status))}</span><small>${esc(x.note||"")}</small></div>`).join("")}</div>`:"");}
function renderBoundary(){if(!state.results.blue_opening)return "";return `<section class="panel boundaryPanel"><details open><summary><strong>判断境界</strong></summary><div class="miniGrid"><div>${chips("判断基準",state.decisionBoundary.criteria.map(x=>`${x.id} ${x.text}`))}</div><div>${list("制約",state.deterministic.constraints.map(x=>`${x.id} ${x.text}`))}</div><div>${list("対象外",state.decisionBoundary.outOfScope.map(x=>`${x.id} ${x.text}`))}</div></div></details></section>`;}
function renderCard(h){
  const m=state.resultMeta[h.id]||freshResultMeta(),r=state.results[h.id];const warnings=normalizeWarnings(m.validation?.warnings,h.id);const stateLabel=formatStatus(m.status);const next=HAT_IDS[HAT_IDS.indexOf(h.id)+1];
  let body="";
  if(m.status==="generating")body=`<div class="emptyState"><strong>${esc(formatPhase(m.phase))}</strong><div class="phaseTimer">経過時間 <span data-elapsed="${h.id}">00:00</span></div><div>試行 ${Math.max(1,m.generation.attemptCount+1)} / 2</div></div>`;
  else if(r)body=warningHtml(warnings)+renderResult(h.id,r);
  else if(m.status==="interrupted")body='<div class="notice error">実行中に中断されました。再開または再生成してください。</div>';
  else body='<div class="emptyState">まだ実行されていません。</div>';
  const meta=r?`<div class="metaRow"><span class="metaBadge ${m.status}">${esc(stateLabel)}</span>${m.schemaVariant?`<span class="metaBadge">Schema ${esc(m.schemaVariant)}</span>`:""}${m.generation?.durationMs?`<span class="metaBadge">${esc(formatElapsed(m.generation.durationMs))}</span>`:""}${h.id==="red"&&r.otherStakeholdersSummary?`<span class="metaBadge">個別 ${r.stakeholders.length}／集約 ${r.otherStakeholdersSummary.coveredStakeholderIds.length}</span>`:""}</div>`:"";
  let actions="";
  if(m.status==="generating")actions=`<button class="btn danger" data-act="stop" data-hat="${h.id}">中止</button>`;
  else if(r)actions=`<button class="btn small" data-act="edit" data-hat="${h.id}">編集</button><button class="btn small" data-act="regen" data-hat="${h.id}">再生成</button><button class="btn small" data-act="deep" data-hat="${h.id}">深掘り</button><button class="btn small" data-act="important" data-hat="${h.id}">${state.meta.important.includes(h.id)?"重要解除":"重要"}</button><button class="btn small" data-act="exclude" data-hat="${h.id}">${state.meta.excluded.includes(h.id)?"除外解除":"除外"}</button><button class="btn small" data-act="copy" data-hat="${h.id}">JSONコピー</button><button class="btn small" data-act="details" data-hat="${h.id}">詳細</button>${warnings.length?`<button class="btn small" data-act="accept" data-hat="${h.id}">警告を確認済み</button>`:""}${state.input.mode==="standard"&&next&&m.status!=="stale"?`<button class="btn primary" data-act="next" data-hat="${next}">次へ：${esc(HATS.find(x=>x.id===next).short)}</button>`:""}`;
  else if(["invalid","interrupted","stale"].includes(m.status))actions=`<button class="btn primary" data-act="regen" data-hat="${h.id}">再実行</button>`;
  return `<section class="hatCard" style="--hat:${h.color}"><div class="hatHead"><div class="hatIcon ${h.white?"white":""}">${h.icon}</div><div class="hatTitle"><h2>${esc(h.name)}：${esc(h.short)}</h2><p>${esc(h.role)}</p></div><div class="hatState">${esc(stateLabel)}</div></div><div class="hatBody">${meta}${body}</div><div class="hatActions">${actions}</div></section>`;
}
function renderProgress(){const done=completedCount(),pct=Math.round(done/HAT_IDS.length*100);$("#progressBar").style.width=`${pct}%`;const phase=state.meta.currentHat?`${HATS.find(x=>x.id===state.meta.currentHat)?.short||""}：${formatPhase(state.meta.phase)} <span id="liveElapsed">00:00</span>`:`${done} / 7 完了`;$("#progressText").innerHTML=phase;$("#progressWrap").classList.toggle("show",Boolean(state.meta.currentHat)||done>0);}
function renderAll(){renderSidebar();$("#cards").innerHTML=renderBoundary()+HATS.map(renderCard).join("");renderProgress();bindCardActions();updateTitle();}
function bindCardActions(){$$("[data-act]").forEach(b=>b.onclick=async()=>{const act=b.dataset.act,h=b.dataset.hat;if(act==="edit")openEdit(h);if(act==="next"){if(!currentRunId||["complete","failed","aborted"].includes(state.runSummary?.status))createRun("standard",{parentRunId:state.runSummary?.runId||null});else if(state.runSummary)state.runSummary.status="running";await runHat(h,{workflow:true});}if(act==="regen")await runHat(h,{regenerate:true});if(act==="deep")await runHat(h,{deep:true});if(act==="important"){toggleMeta("important",h);markDependentsStale(h,true);renderAll();await queueAutosave("important-toggle");}if(act==="exclude"){toggleMeta("excluded",h);if(state.results.blue_closing)markDependentsStale(h,true);renderAll();await queueAutosave("exclude-toggle");}if(act==="copy")navigator.clipboard.writeText(JSON.stringify(state.results[h],null,2));if(act==="accept"){for(const w of arr(state.resultMeta[h].validation.warnings))w.acknowledged=true;state.resultMeta[h].userAcceptedWarnings=true;debugLog("user-accepted-warning",{hatId:h});renderAll();await queueAutosave("warning-accepted");}if(act==="details")openResultDetails(h);if(act==="stop")stopGeneration();});}
function toggleMeta(k,h){const a=state.meta[k]||[];state.meta[k]=a.includes(h)?a.filter(x=>x!==h):[...a,h];}

function syncInputs(){for(const id of ["topic","context","constraints","stakeholders","desiredOutcome","focus","detail","mode","warningPolicy"]){const el=$("#"+id);if(el)el.value=state.input[id]??"";}updateTitle();}
function pullInputs(){for(const id of ["topic","context","constraints","stakeholders","desiredOutcome","focus","detail","mode","warningPolicy"]){const el=$("#"+id);if(el)state.input[id]=el.value;}state.updatedAt=now();}
function bindInput(){for(const id of ["topic","context","constraints","stakeholders","desiredOutcome","focus","detail","mode","warningPolicy"]){const el=$("#"+id);if(el)el.addEventListener("input",()=>{pullInputs();updateTitle();});}}
function clearInputs(){for(const id of ["topic","context","constraints","stakeholders","focus"]){const el=$("#"+id);if(el)el.value="";}pullInputs();updateTitle();}
function sample(){Object.assign(state.input,{topic:"自治体は製品プラスチックの分別収集を開始すべきか",context:"現在は容器包装プラスチックのみを分別収集している。中間処理施設の余力は小さい。人口は約10万人で、令和10年度の開始を検討している。",constraints:"新たな大型施設整備は当面困難。住民負担と収集運搬費の増加を抑える必要がある。",stakeholders:"住民、収集運搬事業者、中間処理施設、自治体担当者、議会、再商品化事業者",desiredOutcome:"推奨判断",focus:"コスト、実現性、資源化効果、住民負担、処理安定性",detail:"standard",mode:"standard",warningPolicy:"review_required"});syncInputs();}
function newMeeting(){if(Object.keys(state.results).length){openNewMeetingDialog();return;}resetMeeting();}
function resetMeeting(){stopGeneration();destroyBaseSession();state=freshState();currentRunId=null;syncInputs();renderAll();$("#progressWrap").classList.remove("show");window.scrollTo({top:0,behavior:"smooth"});}
async function saveLocal(){pullInputs();await queueAutosave("manual-save");showGlobalNotice(state.meta.autosaveStatus==="保存済み"?"ブラウザに保存しました。":"保存に失敗しました。",state.meta.autosaveStatus==="保存済み"?"warn":"error");}
function renderHistory(){let all={};try{all=JSON.parse(storage.getItem(STORAGE_KEY)||"{}");}catch{}const items=Object.values(all).sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||""));$("#historyList").innerHTML=items.length?items.map(x=>`<div class="historyItem"><div><h3>${esc(x.input?.topic||"無題")}</h3><p>${new Date(x.updatedAt).toLocaleString("ja-JP")} ・ ${Object.keys(x.results||{}).length}/7 結果 ・ v${esc(x.build?.appVersion||x.appVersion||"?")}</p></div><button class="btn small" data-load="${x.id}">開く</button><button class="btn small danger" data-delete="${x.id}">削除</button></div>`).join(""):'<div class="emptyState">保存済みの会議はありません。</div>';$$('[data-load]').forEach(b=>b.onclick=()=>{state=migrateState(all[b.dataset.load],"history");currentRunId=state.runSummary?.runId||null;syncInputs();renderAll();$("#historyDialog").close();});$$('[data-delete]').forEach(b=>b.onclick=()=>{delete all[b.dataset.delete];storage.setItem(STORAGE_KEY,JSON.stringify(all));renderHistory();});}
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function markdown(){let s=`# 6色思考会議\n\n- アプリ: ${state.build.appVersion}\n- Schema: ${state.build.schemaVersion}\n- Run ID: ${state.runSummary?.runId||"—"}\n\n## 議題\n${state.input.topic}\n\n## 背景・前提\n${state.input.context||"—"}\n\n`;for(const h of HATS){const r=state.results[h.id];if(!r)continue;s+=`## ${h.name}：${h.short}\n\n\`\`\`json\n${JSON.stringify(r,null,2)}\n\`\`\`\n\n`;}return s;}
